/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AccountExistsIdentifierParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountExistsIdentifierParameter{}

// AccountExistsIdentifierParameter struct for AccountExistsIdentifierParameter
type AccountExistsIdentifierParameter struct {
	// The type of identifier
	IdentifierType string `json:"identifier_type"`
	// The value of the identifier. The value must be valid for the specified `identifier_type`
	IdentifierValue string `json:"identifier_value"`
}

// NewAccountExistsIdentifierParameter instantiates a new AccountExistsIdentifierParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountExistsIdentifierParameter(identifierType string, identifierValue string) *AccountExistsIdentifierParameter {
	this := AccountExistsIdentifierParameter{}
	this.IdentifierType = identifierType
	this.IdentifierValue = identifierValue
	return &this
}

// NewAccountExistsIdentifierParameterWithDefaults instantiates a new AccountExistsIdentifierParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountExistsIdentifierParameterWithDefaults() *AccountExistsIdentifierParameter {
	this := AccountExistsIdentifierParameter{}
	return &this
}

// GetIdentifierType returns the IdentifierType field value
func (o *AccountExistsIdentifierParameter) GetIdentifierType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentifierType
}

// GetIdentifierTypeOk returns a tuple with the IdentifierType field value
// and a boolean to check if the value has been set.
func (o *AccountExistsIdentifierParameter) GetIdentifierTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentifierType, true
}

// SetIdentifierType sets field value
func (o *AccountExistsIdentifierParameter) SetIdentifierType(v string) {
	o.IdentifierType = v
}

// GetIdentifierValue returns the IdentifierValue field value
func (o *AccountExistsIdentifierParameter) GetIdentifierValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentifierValue
}

// GetIdentifierValueOk returns a tuple with the IdentifierValue field value
// and a boolean to check if the value has been set.
func (o *AccountExistsIdentifierParameter) GetIdentifierValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentifierValue, true
}

// SetIdentifierValue sets field value
func (o *AccountExistsIdentifierParameter) SetIdentifierValue(v string) {
	o.IdentifierValue = v
}

func (o AccountExistsIdentifierParameter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountExistsIdentifierParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier_type"] = o.IdentifierType
	toSerialize["identifier_value"] = o.IdentifierValue
	return toSerialize, nil
}

type NullableAccountExistsIdentifierParameter struct {
	value *AccountExistsIdentifierParameter
	isSet bool
}

func (v NullableAccountExistsIdentifierParameter) Get() *AccountExistsIdentifierParameter {
	return v.value
}

func (v *NullableAccountExistsIdentifierParameter) Set(val *AccountExistsIdentifierParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountExistsIdentifierParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountExistsIdentifierParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountExistsIdentifierParameter(val *AccountExistsIdentifierParameter) *NullableAccountExistsIdentifierParameter {
	return &NullableAccountExistsIdentifierParameter{value: val, isSet: true}
}

func (v NullableAccountExistsIdentifierParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountExistsIdentifierParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


