/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodInitializeResponseAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodInitializeResponseAction{}

// PaymentMethodInitializeResponseAction struct for PaymentMethodInitializeResponseAction
type PaymentMethodInitializeResponseAction struct {
	Type *string `json:"type,omitempty"`
	Url *string `json:"url,omitempty"`
	Method *string `json:"method,omitempty"`
}

// NewPaymentMethodInitializeResponseAction instantiates a new PaymentMethodInitializeResponseAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodInitializeResponseAction() *PaymentMethodInitializeResponseAction {
	this := PaymentMethodInitializeResponseAction{}
	return &this
}

// NewPaymentMethodInitializeResponseActionWithDefaults instantiates a new PaymentMethodInitializeResponseAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodInitializeResponseActionWithDefaults() *PaymentMethodInitializeResponseAction {
	this := PaymentMethodInitializeResponseAction{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PaymentMethodInitializeResponseAction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodInitializeResponseAction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PaymentMethodInitializeResponseAction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PaymentMethodInitializeResponseAction) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PaymentMethodInitializeResponseAction) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodInitializeResponseAction) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PaymentMethodInitializeResponseAction) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PaymentMethodInitializeResponseAction) SetUrl(v string) {
	o.Url = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *PaymentMethodInitializeResponseAction) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodInitializeResponseAction) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *PaymentMethodInitializeResponseAction) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *PaymentMethodInitializeResponseAction) SetMethod(v string) {
	o.Method = &v
}

func (o PaymentMethodInitializeResponseAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodInitializeResponseAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	return toSerialize, nil
}

type NullablePaymentMethodInitializeResponseAction struct {
	value *PaymentMethodInitializeResponseAction
	isSet bool
}

func (v NullablePaymentMethodInitializeResponseAction) Get() *PaymentMethodInitializeResponseAction {
	return v.value
}

func (v *NullablePaymentMethodInitializeResponseAction) Set(val *PaymentMethodInitializeResponseAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodInitializeResponseAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodInitializeResponseAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodInitializeResponseAction(val *PaymentMethodInitializeResponseAction) *NullablePaymentMethodInitializeResponseAction {
	return &NullablePaymentMethodInitializeResponseAction{value: val, isSet: true}
}

func (v NullablePaymentMethodInitializeResponseAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodInitializeResponseAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


