/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IdentifiersMerchantDivisionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentifiersMerchantDivisionsInner{}

// IdentifiersMerchantDivisionsInner struct for IdentifiersMerchantDivisionsInner
type IdentifiersMerchantDivisionsInner struct {
	PublishableKey string `json:"publishable_key"`
}

// NewIdentifiersMerchantDivisionsInner instantiates a new IdentifiersMerchantDivisionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifiersMerchantDivisionsInner(publishableKey string) *IdentifiersMerchantDivisionsInner {
	this := IdentifiersMerchantDivisionsInner{}
	this.PublishableKey = publishableKey
	return &this
}

// NewIdentifiersMerchantDivisionsInnerWithDefaults instantiates a new IdentifiersMerchantDivisionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifiersMerchantDivisionsInnerWithDefaults() *IdentifiersMerchantDivisionsInner {
	this := IdentifiersMerchantDivisionsInner{}
	return &this
}

// GetPublishableKey returns the PublishableKey field value
func (o *IdentifiersMerchantDivisionsInner) GetPublishableKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublishableKey
}

// GetPublishableKeyOk returns a tuple with the PublishableKey field value
// and a boolean to check if the value has been set.
func (o *IdentifiersMerchantDivisionsInner) GetPublishableKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublishableKey, true
}

// SetPublishableKey sets field value
func (o *IdentifiersMerchantDivisionsInner) SetPublishableKey(v string) {
	o.PublishableKey = v
}

func (o IdentifiersMerchantDivisionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentifiersMerchantDivisionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["publishable_key"] = o.PublishableKey
	return toSerialize, nil
}

type NullableIdentifiersMerchantDivisionsInner struct {
	value *IdentifiersMerchantDivisionsInner
	isSet bool
}

func (v NullableIdentifiersMerchantDivisionsInner) Get() *IdentifiersMerchantDivisionsInner {
	return v.value
}

func (v *NullableIdentifiersMerchantDivisionsInner) Set(val *IdentifiersMerchantDivisionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifiersMerchantDivisionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifiersMerchantDivisionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifiersMerchantDivisionsInner(val *IdentifiersMerchantDivisionsInner) *NullableIdentifiersMerchantDivisionsInner {
	return &NullableIdentifiersMerchantDivisionsInner{value: val, isSet: true}
}

func (v NullableIdentifiersMerchantDivisionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifiersMerchantDivisionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


