/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ShipmentTrackingUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShipmentTrackingUpdate{}

// ShipmentTrackingUpdate struct for ShipmentTrackingUpdate
type ShipmentTrackingUpdate struct {
	// The carrier's tracking number for the shipment. Must be prefixed with `MockBolt`.
	TrackingNumber string `json:"tracking_number"`
	// A list of tracking updates that contain the shipment's status, location, and any unique messages.
	TrackingDetails []ShipmentTrackingUpdateTrackingDetailsInner `json:"tracking_details"`
	// The shipment's status.
	Status string `json:"status"`
	// The shipment's actual or estimated delivery date.
	DeliveryDate *time.Time `json:"delivery_date,omitempty"`
}

// NewShipmentTrackingUpdate instantiates a new ShipmentTrackingUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentTrackingUpdate(trackingNumber string, trackingDetails []ShipmentTrackingUpdateTrackingDetailsInner, status string) *ShipmentTrackingUpdate {
	this := ShipmentTrackingUpdate{}
	this.TrackingNumber = trackingNumber
	this.TrackingDetails = trackingDetails
	this.Status = status
	return &this
}

// NewShipmentTrackingUpdateWithDefaults instantiates a new ShipmentTrackingUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentTrackingUpdateWithDefaults() *ShipmentTrackingUpdate {
	this := ShipmentTrackingUpdate{}
	return &this
}

// GetTrackingNumber returns the TrackingNumber field value
func (o *ShipmentTrackingUpdate) GetTrackingNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value
// and a boolean to check if the value has been set.
func (o *ShipmentTrackingUpdate) GetTrackingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingNumber, true
}

// SetTrackingNumber sets field value
func (o *ShipmentTrackingUpdate) SetTrackingNumber(v string) {
	o.TrackingNumber = v
}

// GetTrackingDetails returns the TrackingDetails field value
func (o *ShipmentTrackingUpdate) GetTrackingDetails() []ShipmentTrackingUpdateTrackingDetailsInner {
	if o == nil {
		var ret []ShipmentTrackingUpdateTrackingDetailsInner
		return ret
	}

	return o.TrackingDetails
}

// GetTrackingDetailsOk returns a tuple with the TrackingDetails field value
// and a boolean to check if the value has been set.
func (o *ShipmentTrackingUpdate) GetTrackingDetailsOk() ([]ShipmentTrackingUpdateTrackingDetailsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrackingDetails, true
}

// SetTrackingDetails sets field value
func (o *ShipmentTrackingUpdate) SetTrackingDetails(v []ShipmentTrackingUpdateTrackingDetailsInner) {
	o.TrackingDetails = v
}

// GetStatus returns the Status field value
func (o *ShipmentTrackingUpdate) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ShipmentTrackingUpdate) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ShipmentTrackingUpdate) SetStatus(v string) {
	o.Status = v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise.
func (o *ShipmentTrackingUpdate) GetDeliveryDate() time.Time {
	if o == nil || IsNil(o.DeliveryDate) {
		var ret time.Time
		return ret
	}
	return *o.DeliveryDate
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentTrackingUpdate) GetDeliveryDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeliveryDate) {
		return nil, false
	}
	return o.DeliveryDate, true
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *ShipmentTrackingUpdate) HasDeliveryDate() bool {
	if o != nil && !IsNil(o.DeliveryDate) {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given time.Time and assigns it to the DeliveryDate field.
func (o *ShipmentTrackingUpdate) SetDeliveryDate(v time.Time) {
	o.DeliveryDate = &v
}

func (o ShipmentTrackingUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShipmentTrackingUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tracking_number"] = o.TrackingNumber
	toSerialize["tracking_details"] = o.TrackingDetails
	toSerialize["status"] = o.Status
	if !IsNil(o.DeliveryDate) {
		toSerialize["delivery_date"] = o.DeliveryDate
	}
	return toSerialize, nil
}

type NullableShipmentTrackingUpdate struct {
	value *ShipmentTrackingUpdate
	isSet bool
}

func (v NullableShipmentTrackingUpdate) Get() *ShipmentTrackingUpdate {
	return v.value
}

func (v *NullableShipmentTrackingUpdate) Set(val *ShipmentTrackingUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentTrackingUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentTrackingUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentTrackingUpdate(val *ShipmentTrackingUpdate) *NullableShipmentTrackingUpdate {
	return &NullableShipmentTrackingUpdate{value: val, isSet: true}
}

func (v NullableShipmentTrackingUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentTrackingUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


