/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventList{}

// EventList struct for EventList
type EventList struct {
	Tag string `json:".tag"`
	EventList []string `json:"event_list"`
}

// NewEventList instantiates a new EventList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventList(tag string, eventList []string) *EventList {
	this := EventList{}
	this.Tag = tag
	this.EventList = eventList
	return &this
}

// NewEventListWithDefaults instantiates a new EventList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventListWithDefaults() *EventList {
	this := EventList{}
	return &this
}

// GetTag returns the Tag field value
func (o *EventList) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *EventList) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *EventList) SetTag(v string) {
	o.Tag = v
}

// GetEventList returns the EventList field value
func (o *EventList) GetEventList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EventList
}

// GetEventListOk returns a tuple with the EventList field value
// and a boolean to check if the value has been set.
func (o *EventList) GetEventListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventList, true
}

// SetEventList sets field value
func (o *EventList) SetEventList(v []string) {
	o.EventList = v
}

func (o EventList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize[".tag"] = o.Tag
	toSerialize["event_list"] = o.EventList
	return toSerialize, nil
}

type NullableEventList struct {
	value *EventList
	isSet bool
}

func (v NullableEventList) Get() *EventList {
	return v.value
}

func (v *NullableEventList) Set(val *EventList) {
	v.value = val
	v.isSet = true
}

func (v NullableEventList) IsSet() bool {
	return v.isSet
}

func (v *NullableEventList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventList(val *EventList) *NullableEventList {
	return &NullableEventList{value: val, isSet: true}
}

func (v NullableEventList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


