/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodInitializeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodInitializeRequest{}

// PaymentMethodInitializeRequest struct for PaymentMethodInitializeRequest
type PaymentMethodInitializeRequest struct {
	Cart Cart `json:"cart"`
	PaymentMethod PaymentMethodInitializeRequestPaymentMethod `json:"payment_method"`
}

// NewPaymentMethodInitializeRequest instantiates a new PaymentMethodInitializeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodInitializeRequest(cart Cart, paymentMethod PaymentMethodInitializeRequestPaymentMethod) *PaymentMethodInitializeRequest {
	this := PaymentMethodInitializeRequest{}
	this.Cart = cart
	this.PaymentMethod = paymentMethod
	return &this
}

// NewPaymentMethodInitializeRequestWithDefaults instantiates a new PaymentMethodInitializeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodInitializeRequestWithDefaults() *PaymentMethodInitializeRequest {
	this := PaymentMethodInitializeRequest{}
	return &this
}

// GetCart returns the Cart field value
func (o *PaymentMethodInitializeRequest) GetCart() Cart {
	if o == nil {
		var ret Cart
		return ret
	}

	return o.Cart
}

// GetCartOk returns a tuple with the Cart field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodInitializeRequest) GetCartOk() (*Cart, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cart, true
}

// SetCart sets field value
func (o *PaymentMethodInitializeRequest) SetCart(v Cart) {
	o.Cart = v
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *PaymentMethodInitializeRequest) GetPaymentMethod() PaymentMethodInitializeRequestPaymentMethod {
	if o == nil {
		var ret PaymentMethodInitializeRequestPaymentMethod
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodInitializeRequest) GetPaymentMethodOk() (*PaymentMethodInitializeRequestPaymentMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *PaymentMethodInitializeRequest) SetPaymentMethod(v PaymentMethodInitializeRequestPaymentMethod) {
	o.PaymentMethod = v
}

func (o PaymentMethodInitializeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodInitializeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cart"] = o.Cart
	toSerialize["payment_method"] = o.PaymentMethod
	return toSerialize, nil
}

type NullablePaymentMethodInitializeRequest struct {
	value *PaymentMethodInitializeRequest
	isSet bool
}

func (v NullablePaymentMethodInitializeRequest) Get() *PaymentMethodInitializeRequest {
	return v.value
}

func (v *NullablePaymentMethodInitializeRequest) Set(val *PaymentMethodInitializeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodInitializeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodInitializeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodInitializeRequest(val *PaymentMethodInitializeRequest) *NullablePaymentMethodInitializeRequest {
	return &NullablePaymentMethodInitializeRequest{value: val, isSet: true}
}

func (v NullablePaymentMethodInitializeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodInitializeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


