/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebhooksPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhooksPostRequest{}

// WebhooksPostRequest struct for WebhooksPostRequest
type WebhooksPostRequest struct {
	Message string `json:"message"`
}

// NewWebhooksPostRequest instantiates a new WebhooksPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksPostRequest(message string) *WebhooksPostRequest {
	this := WebhooksPostRequest{}
	this.Message = message
	return &this
}

// NewWebhooksPostRequestWithDefaults instantiates a new WebhooksPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksPostRequestWithDefaults() *WebhooksPostRequest {
	this := WebhooksPostRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *WebhooksPostRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *WebhooksPostRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *WebhooksPostRequest) SetMessage(v string) {
	o.Message = v
}

func (o WebhooksPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhooksPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

type NullableWebhooksPostRequest struct {
	value *WebhooksPostRequest
	isSet bool
}

func (v NullableWebhooksPostRequest) Get() *WebhooksPostRequest {
	return v.value
}

func (v *NullableWebhooksPostRequest) Set(val *WebhooksPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksPostRequest(val *WebhooksPostRequest) *NullableWebhooksPostRequest {
	return &NullableWebhooksPostRequest{value: val, isSet: true}
}

func (v NullableWebhooksPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhooksPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


