/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodCreditCard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodCreditCard{}

// PaymentMethodCreditCard struct for PaymentMethodCreditCard
type PaymentMethodCreditCard struct {
	Tag string `json:".tag"`
	Id *string `json:"id,omitempty"`
	// Credit card type
	Type string `json:"type"`
	BillingAddressInput *AddressReference `json:"billing_address_input,omitempty"`
	// The ID of credit card's billing address
	BillingAddressId *string `json:"billing_address_id,omitempty"`
	// The credit card network.
	Network string `json:"network"`
	// The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
	Expiration string `json:"expiration"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
}

// NewPaymentMethodCreditCard instantiates a new PaymentMethodCreditCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodCreditCard(tag string, type_ string, network string, bin string, last4 string, expiration string, token string) *PaymentMethodCreditCard {
	this := PaymentMethodCreditCard{}
	this.Tag = tag
	this.Type = type_
	this.Network = network
	this.Bin = bin
	this.Last4 = last4
	this.Expiration = expiration
	this.Token = token
	return &this
}

// NewPaymentMethodCreditCardWithDefaults instantiates a new PaymentMethodCreditCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodCreditCardWithDefaults() *PaymentMethodCreditCard {
	this := PaymentMethodCreditCard{}
	return &this
}

// GetTag returns the Tag field value
func (o *PaymentMethodCreditCard) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *PaymentMethodCreditCard) SetTag(v string) {
	o.Tag = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentMethodCreditCard) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentMethodCreditCard) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentMethodCreditCard) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value
func (o *PaymentMethodCreditCard) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PaymentMethodCreditCard) SetType(v string) {
	o.Type = v
}

// GetBillingAddressInput returns the BillingAddressInput field value if set, zero value otherwise.
func (o *PaymentMethodCreditCard) GetBillingAddressInput() AddressReference {
	if o == nil || IsNil(o.BillingAddressInput) {
		var ret AddressReference
		return ret
	}
	return *o.BillingAddressInput
}

// GetBillingAddressInputOk returns a tuple with the BillingAddressInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetBillingAddressInputOk() (*AddressReference, bool) {
	if o == nil || IsNil(o.BillingAddressInput) {
		return nil, false
	}
	return o.BillingAddressInput, true
}

// HasBillingAddressInput returns a boolean if a field has been set.
func (o *PaymentMethodCreditCard) HasBillingAddressInput() bool {
	if o != nil && !IsNil(o.BillingAddressInput) {
		return true
	}

	return false
}

// SetBillingAddressInput gets a reference to the given AddressReference and assigns it to the BillingAddressInput field.
func (o *PaymentMethodCreditCard) SetBillingAddressInput(v AddressReference) {
	o.BillingAddressInput = &v
}

// GetBillingAddressId returns the BillingAddressId field value if set, zero value otherwise.
func (o *PaymentMethodCreditCard) GetBillingAddressId() string {
	if o == nil || IsNil(o.BillingAddressId) {
		var ret string
		return ret
	}
	return *o.BillingAddressId
}

// GetBillingAddressIdOk returns a tuple with the BillingAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetBillingAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAddressId) {
		return nil, false
	}
	return o.BillingAddressId, true
}

// HasBillingAddressId returns a boolean if a field has been set.
func (o *PaymentMethodCreditCard) HasBillingAddressId() bool {
	if o != nil && !IsNil(o.BillingAddressId) {
		return true
	}

	return false
}

// SetBillingAddressId gets a reference to the given string and assigns it to the BillingAddressId field.
func (o *PaymentMethodCreditCard) SetBillingAddressId(v string) {
	o.BillingAddressId = &v
}

// GetNetwork returns the Network field value
func (o *PaymentMethodCreditCard) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *PaymentMethodCreditCard) SetNetwork(v string) {
	o.Network = v
}

// GetBin returns the Bin field value
func (o *PaymentMethodCreditCard) GetBin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bin
}

// GetBinOk returns a tuple with the Bin field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetBinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bin, true
}

// SetBin sets field value
func (o *PaymentMethodCreditCard) SetBin(v string) {
	o.Bin = v
}

// GetLast4 returns the Last4 field value
func (o *PaymentMethodCreditCard) GetLast4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Last4
}

// GetLast4Ok returns a tuple with the Last4 field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetLast4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last4, true
}

// SetLast4 sets field value
func (o *PaymentMethodCreditCard) SetLast4(v string) {
	o.Last4 = v
}

// GetExpiration returns the Expiration field value
func (o *PaymentMethodCreditCard) GetExpiration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetExpirationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *PaymentMethodCreditCard) SetExpiration(v string) {
	o.Expiration = v
}

// GetToken returns the Token field value
func (o *PaymentMethodCreditCard) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCard) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *PaymentMethodCreditCard) SetToken(v string) {
	o.Token = v
}

func (o PaymentMethodCreditCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodCreditCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize[".tag"] = o.Tag
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.BillingAddressInput) {
		toSerialize["billing_address_input"] = o.BillingAddressInput
	}
	if !IsNil(o.BillingAddressId) {
		toSerialize["billing_address_id"] = o.BillingAddressId
	}
	toSerialize["network"] = o.Network
	toSerialize["bin"] = o.Bin
	toSerialize["last4"] = o.Last4
	toSerialize["expiration"] = o.Expiration
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullablePaymentMethodCreditCard struct {
	value *PaymentMethodCreditCard
	isSet bool
}

func (v NullablePaymentMethodCreditCard) Get() *PaymentMethodCreditCard {
	return v.value
}

func (v *NullablePaymentMethodCreditCard) Set(val *PaymentMethodCreditCard) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodCreditCard) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodCreditCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodCreditCard(val *PaymentMethodCreditCard) *NullablePaymentMethodCreditCard {
	return &NullablePaymentMethodCreditCard{value: val, isSet: true}
}

func (v NullablePaymentMethodCreditCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodCreditCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


