/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// WebhookEvent - struct for WebhookEvent
type WebhookEvent struct {
	EventGroup *EventGroup
	EventList *EventList
}

// EventGroupAsWebhookEvent is a convenience function that returns EventGroup wrapped in WebhookEvent
func EventGroupAsWebhookEvent(v *EventGroup) WebhookEvent {
	return WebhookEvent{
		EventGroup: v,
	}
}

// EventListAsWebhookEvent is a convenience function that returns EventList wrapped in WebhookEvent
func EventListAsWebhookEvent(v *EventList) WebhookEvent {
	return WebhookEvent{
		EventList: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *WebhookEvent) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EventGroup
	err = newStrictDecoder(data).Decode(&dst.EventGroup)
	if err == nil {
		jsonEventGroup, _ := json.Marshal(dst.EventGroup)
		if string(jsonEventGroup) == "{}" { // empty struct
			dst.EventGroup = nil
		} else {
			match++
		}
	} else {
		dst.EventGroup = nil
	}

	// try to unmarshal data into EventList
	err = newStrictDecoder(data).Decode(&dst.EventList)
	if err == nil {
		jsonEventList, _ := json.Marshal(dst.EventList)
		if string(jsonEventList) == "{}" { // empty struct
			dst.EventList = nil
		} else {
			match++
		}
	} else {
		dst.EventList = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EventGroup = nil
		dst.EventList = nil

		return fmt.Errorf("data matches more than one schema in oneOf(WebhookEvent)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(WebhookEvent)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src WebhookEvent) MarshalJSON() ([]byte, error) {
	if src.EventGroup != nil {
		return json.Marshal(&src.EventGroup)
	}

	if src.EventList != nil {
		return json.Marshal(&src.EventList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *WebhookEvent) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EventGroup != nil {
		return obj.EventGroup
	}

	if obj.EventList != nil {
		return obj.EventList
	}

	// all schemas are nil
	return nil
}

type NullableWebhookEvent struct {
	value *WebhookEvent
	isSet bool
}

func (v NullableWebhookEvent) Get() *WebhookEvent {
	return v.value
}

func (v *NullableWebhookEvent) Set(val *WebhookEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEvent(val *WebhookEvent) *NullableWebhookEvent {
	return &NullableWebhookEvent{value: val, isSet: true}
}

func (v NullableWebhookEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


