/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodCreditCardAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodCreditCardAllOf{}

// PaymentMethodCreditCardAllOf struct for PaymentMethodCreditCardAllOf
type PaymentMethodCreditCardAllOf struct {
	Tag string `json:".tag"`
	Id *string `json:"id,omitempty"`
	// Credit card type
	Type string `json:"type"`
	BillingAddressInput *AddressReference `json:"billing_address_input,omitempty"`
	// The ID of credit card's billing address
	BillingAddressId *string `json:"billing_address_id,omitempty"`
}

// NewPaymentMethodCreditCardAllOf instantiates a new PaymentMethodCreditCardAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodCreditCardAllOf(tag string, type_ string) *PaymentMethodCreditCardAllOf {
	this := PaymentMethodCreditCardAllOf{}
	this.Tag = tag
	this.Type = type_
	return &this
}

// NewPaymentMethodCreditCardAllOfWithDefaults instantiates a new PaymentMethodCreditCardAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodCreditCardAllOfWithDefaults() *PaymentMethodCreditCardAllOf {
	this := PaymentMethodCreditCardAllOf{}
	return &this
}

// GetTag returns the Tag field value
func (o *PaymentMethodCreditCardAllOf) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCardAllOf) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *PaymentMethodCreditCardAllOf) SetTag(v string) {
	o.Tag = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentMethodCreditCardAllOf) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCardAllOf) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentMethodCreditCardAllOf) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentMethodCreditCardAllOf) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value
func (o *PaymentMethodCreditCardAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCardAllOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PaymentMethodCreditCardAllOf) SetType(v string) {
	o.Type = v
}

// GetBillingAddressInput returns the BillingAddressInput field value if set, zero value otherwise.
func (o *PaymentMethodCreditCardAllOf) GetBillingAddressInput() AddressReference {
	if o == nil || IsNil(o.BillingAddressInput) {
		var ret AddressReference
		return ret
	}
	return *o.BillingAddressInput
}

// GetBillingAddressInputOk returns a tuple with the BillingAddressInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCardAllOf) GetBillingAddressInputOk() (*AddressReference, bool) {
	if o == nil || IsNil(o.BillingAddressInput) {
		return nil, false
	}
	return o.BillingAddressInput, true
}

// HasBillingAddressInput returns a boolean if a field has been set.
func (o *PaymentMethodCreditCardAllOf) HasBillingAddressInput() bool {
	if o != nil && !IsNil(o.BillingAddressInput) {
		return true
	}

	return false
}

// SetBillingAddressInput gets a reference to the given AddressReference and assigns it to the BillingAddressInput field.
func (o *PaymentMethodCreditCardAllOf) SetBillingAddressInput(v AddressReference) {
	o.BillingAddressInput = &v
}

// GetBillingAddressId returns the BillingAddressId field value if set, zero value otherwise.
func (o *PaymentMethodCreditCardAllOf) GetBillingAddressId() string {
	if o == nil || IsNil(o.BillingAddressId) {
		var ret string
		return ret
	}
	return *o.BillingAddressId
}

// GetBillingAddressIdOk returns a tuple with the BillingAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodCreditCardAllOf) GetBillingAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillingAddressId) {
		return nil, false
	}
	return o.BillingAddressId, true
}

// HasBillingAddressId returns a boolean if a field has been set.
func (o *PaymentMethodCreditCardAllOf) HasBillingAddressId() bool {
	if o != nil && !IsNil(o.BillingAddressId) {
		return true
	}

	return false
}

// SetBillingAddressId gets a reference to the given string and assigns it to the BillingAddressId field.
func (o *PaymentMethodCreditCardAllOf) SetBillingAddressId(v string) {
	o.BillingAddressId = &v
}

func (o PaymentMethodCreditCardAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodCreditCardAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize[".tag"] = o.Tag
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.BillingAddressInput) {
		toSerialize["billing_address_input"] = o.BillingAddressInput
	}
	if !IsNil(o.BillingAddressId) {
		toSerialize["billing_address_id"] = o.BillingAddressId
	}
	return toSerialize, nil
}

type NullablePaymentMethodCreditCardAllOf struct {
	value *PaymentMethodCreditCardAllOf
	isSet bool
}

func (v NullablePaymentMethodCreditCardAllOf) Get() *PaymentMethodCreditCardAllOf {
	return v.value
}

func (v *NullablePaymentMethodCreditCardAllOf) Set(val *PaymentMethodCreditCardAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodCreditCardAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodCreditCardAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodCreditCardAllOf(val *PaymentMethodCreditCardAllOf) *NullablePaymentMethodCreditCardAllOf {
	return &NullablePaymentMethodCreditCardAllOf{value: val, isSet: true}
}

func (v NullablePaymentMethodCreditCardAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodCreditCardAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


