/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodSavedPaymentMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodSavedPaymentMethod{}

// PaymentMethodSavedPaymentMethod struct for PaymentMethodSavedPaymentMethod
type PaymentMethodSavedPaymentMethod struct {
	Tag string `json:".tag"`
	// Payment ID of the saved Bolt Payment method.
	Id string `json:"id"`
}

// NewPaymentMethodSavedPaymentMethod instantiates a new PaymentMethodSavedPaymentMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodSavedPaymentMethod(tag string, id string) *PaymentMethodSavedPaymentMethod {
	this := PaymentMethodSavedPaymentMethod{}
	this.Tag = tag
	this.Id = id
	return &this
}

// NewPaymentMethodSavedPaymentMethodWithDefaults instantiates a new PaymentMethodSavedPaymentMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodSavedPaymentMethodWithDefaults() *PaymentMethodSavedPaymentMethod {
	this := PaymentMethodSavedPaymentMethod{}
	return &this
}

// GetTag returns the Tag field value
func (o *PaymentMethodSavedPaymentMethod) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodSavedPaymentMethod) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *PaymentMethodSavedPaymentMethod) SetTag(v string) {
	o.Tag = v
}

// GetId returns the Id field value
func (o *PaymentMethodSavedPaymentMethod) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodSavedPaymentMethod) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentMethodSavedPaymentMethod) SetId(v string) {
	o.Id = v
}

func (o PaymentMethodSavedPaymentMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodSavedPaymentMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize[".tag"] = o.Tag
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullablePaymentMethodSavedPaymentMethod struct {
	value *PaymentMethodSavedPaymentMethod
	isSet bool
}

func (v NullablePaymentMethodSavedPaymentMethod) Get() *PaymentMethodSavedPaymentMethod {
	return v.value
}

func (v *NullablePaymentMethodSavedPaymentMethod) Set(val *PaymentMethodSavedPaymentMethod) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodSavedPaymentMethod) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodSavedPaymentMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodSavedPaymentMethod(val *PaymentMethodSavedPaymentMethod) *NullablePaymentMethodSavedPaymentMethod {
	return &NullablePaymentMethodSavedPaymentMethod{value: val, isSet: true}
}

func (v NullablePaymentMethodSavedPaymentMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodSavedPaymentMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


