/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebhooksGetAll200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhooksGetAll200Response{}

// WebhooksGetAll200Response struct for WebhooksGetAll200Response
type WebhooksGetAll200Response struct {
	Webhooks []Webhook `json:"webhooks,omitempty"`
}

// NewWebhooksGetAll200Response instantiates a new WebhooksGetAll200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksGetAll200Response() *WebhooksGetAll200Response {
	this := WebhooksGetAll200Response{}
	return &this
}

// NewWebhooksGetAll200ResponseWithDefaults instantiates a new WebhooksGetAll200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksGetAll200ResponseWithDefaults() *WebhooksGetAll200Response {
	this := WebhooksGetAll200Response{}
	return &this
}

// GetWebhooks returns the Webhooks field value if set, zero value otherwise.
func (o *WebhooksGetAll200Response) GetWebhooks() []Webhook {
	if o == nil || IsNil(o.Webhooks) {
		var ret []Webhook
		return ret
	}
	return o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksGetAll200Response) GetWebhooksOk() ([]Webhook, bool) {
	if o == nil || IsNil(o.Webhooks) {
		return nil, false
	}
	return o.Webhooks, true
}

// HasWebhooks returns a boolean if a field has been set.
func (o *WebhooksGetAll200Response) HasWebhooks() bool {
	if o != nil && !IsNil(o.Webhooks) {
		return true
	}

	return false
}

// SetWebhooks gets a reference to the given []Webhook and assigns it to the Webhooks field.
func (o *WebhooksGetAll200Response) SetWebhooks(v []Webhook) {
	o.Webhooks = v
}

func (o WebhooksGetAll200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhooksGetAll200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Webhooks) {
		toSerialize["webhooks"] = o.Webhooks
	}
	return toSerialize, nil
}

type NullableWebhooksGetAll200Response struct {
	value *WebhooksGetAll200Response
	isSet bool
}

func (v NullableWebhooksGetAll200Response) Get() *WebhooksGetAll200Response {
	return v.value
}

func (v *NullableWebhooksGetAll200Response) Set(val *WebhooksGetAll200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksGetAll200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksGetAll200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksGetAll200Response(val *WebhooksGetAll200Response) *NullableWebhooksGetAll200Response {
	return &NullableWebhooksGetAll200Response{value: val, isSet: true}
}

func (v NullableWebhooksGetAll200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhooksGetAll200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


