/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreditCard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditCard{}

// CreditCard struct for CreditCard
type CreditCard struct {
	// The credit card network.
	Network string `json:"network"`
	// The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
	Expiration string `json:"expiration"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
}

// NewCreditCard instantiates a new CreditCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditCard(network string, bin string, last4 string, expiration string, token string) *CreditCard {
	this := CreditCard{}
	this.Network = network
	this.Bin = bin
	this.Last4 = last4
	this.Expiration = expiration
	this.Token = token
	return &this
}

// NewCreditCardWithDefaults instantiates a new CreditCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditCardWithDefaults() *CreditCard {
	this := CreditCard{}
	return &this
}

// GetNetwork returns the Network field value
func (o *CreditCard) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *CreditCard) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *CreditCard) SetNetwork(v string) {
	o.Network = v
}

// GetBin returns the Bin field value
func (o *CreditCard) GetBin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bin
}

// GetBinOk returns a tuple with the Bin field value
// and a boolean to check if the value has been set.
func (o *CreditCard) GetBinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bin, true
}

// SetBin sets field value
func (o *CreditCard) SetBin(v string) {
	o.Bin = v
}

// GetLast4 returns the Last4 field value
func (o *CreditCard) GetLast4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Last4
}

// GetLast4Ok returns a tuple with the Last4 field value
// and a boolean to check if the value has been set.
func (o *CreditCard) GetLast4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last4, true
}

// SetLast4 sets field value
func (o *CreditCard) SetLast4(v string) {
	o.Last4 = v
}

// GetExpiration returns the Expiration field value
func (o *CreditCard) GetExpiration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *CreditCard) GetExpirationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *CreditCard) SetExpiration(v string) {
	o.Expiration = v
}

// GetToken returns the Token field value
func (o *CreditCard) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CreditCard) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CreditCard) SetToken(v string) {
	o.Token = v
}

func (o CreditCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["bin"] = o.Bin
	toSerialize["last4"] = o.Last4
	toSerialize["expiration"] = o.Expiration
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullableCreditCard struct {
	value *CreditCard
	isSet bool
}

func (v NullableCreditCard) Get() *CreditCard {
	return v.value
}

func (v *NullableCreditCard) Set(val *CreditCard) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditCard) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditCard(val *CreditCard) *NullableCreditCard {
	return &NullableCreditCard{value: val, isSet: true}
}

func (v NullableCreditCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


