/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodPaypal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodPaypal{}

// PaymentMethodPaypal struct for PaymentMethodPaypal
type PaymentMethodPaypal struct {
	Tag string `json:".tag"`
	// Redirect URL for successful PayPal transaction.
	Success string `json:"success"`
	// Redirect URL for canceled PayPal transaction.
	Cancel string `json:"cancel"`
}

// NewPaymentMethodPaypal instantiates a new PaymentMethodPaypal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodPaypal(tag string, success string, cancel string) *PaymentMethodPaypal {
	this := PaymentMethodPaypal{}
	this.Tag = tag
	this.Success = success
	this.Cancel = cancel
	return &this
}

// NewPaymentMethodPaypalWithDefaults instantiates a new PaymentMethodPaypal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodPaypalWithDefaults() *PaymentMethodPaypal {
	this := PaymentMethodPaypal{}
	return &this
}

// GetTag returns the Tag field value
func (o *PaymentMethodPaypal) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPaypal) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *PaymentMethodPaypal) SetTag(v string) {
	o.Tag = v
}

// GetSuccess returns the Success field value
func (o *PaymentMethodPaypal) GetSuccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPaypal) GetSuccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *PaymentMethodPaypal) SetSuccess(v string) {
	o.Success = v
}

// GetCancel returns the Cancel field value
func (o *PaymentMethodPaypal) GetCancel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cancel
}

// GetCancelOk returns a tuple with the Cancel field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPaypal) GetCancelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cancel, true
}

// SetCancel sets field value
func (o *PaymentMethodPaypal) SetCancel(v string) {
	o.Cancel = v
}

func (o PaymentMethodPaypal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodPaypal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize[".tag"] = o.Tag
	toSerialize["success"] = o.Success
	toSerialize["cancel"] = o.Cancel
	return toSerialize, nil
}

type NullablePaymentMethodPaypal struct {
	value *PaymentMethodPaypal
	isSet bool
}

func (v NullablePaymentMethodPaypal) Get() *PaymentMethodPaypal {
	return v.value
}

func (v *NullablePaymentMethodPaypal) Set(val *PaymentMethodPaypal) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodPaypal) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodPaypal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodPaypal(val *PaymentMethodPaypal) *NullablePaymentMethodPaypal {
	return &NullablePaymentMethodPaypal{value: val, isSet: true}
}

func (v NullablePaymentMethodPaypal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodPaypal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


