/*
Bolt API Reference

A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.

API version: 3.0.1
Contact: api-help@bolt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GuestPaymentMethodInitializeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuestPaymentMethodInitializeRequest{}

// GuestPaymentMethodInitializeRequest struct for GuestPaymentMethodInitializeRequest
type GuestPaymentMethodInitializeRequest struct {
	Cart Cart `json:"cart"`
	PaymentMethod GuestPaymentMethodInitializeRequestPaymentMethod `json:"payment_method"`
}

// NewGuestPaymentMethodInitializeRequest instantiates a new GuestPaymentMethodInitializeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuestPaymentMethodInitializeRequest(cart Cart, paymentMethod GuestPaymentMethodInitializeRequestPaymentMethod) *GuestPaymentMethodInitializeRequest {
	this := GuestPaymentMethodInitializeRequest{}
	this.Cart = cart
	this.PaymentMethod = paymentMethod
	return &this
}

// NewGuestPaymentMethodInitializeRequestWithDefaults instantiates a new GuestPaymentMethodInitializeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuestPaymentMethodInitializeRequestWithDefaults() *GuestPaymentMethodInitializeRequest {
	this := GuestPaymentMethodInitializeRequest{}
	return &this
}

// GetCart returns the Cart field value
func (o *GuestPaymentMethodInitializeRequest) GetCart() Cart {
	if o == nil {
		var ret Cart
		return ret
	}

	return o.Cart
}

// GetCartOk returns a tuple with the Cart field value
// and a boolean to check if the value has been set.
func (o *GuestPaymentMethodInitializeRequest) GetCartOk() (*Cart, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cart, true
}

// SetCart sets field value
func (o *GuestPaymentMethodInitializeRequest) SetCart(v Cart) {
	o.Cart = v
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *GuestPaymentMethodInitializeRequest) GetPaymentMethod() GuestPaymentMethodInitializeRequestPaymentMethod {
	if o == nil {
		var ret GuestPaymentMethodInitializeRequestPaymentMethod
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *GuestPaymentMethodInitializeRequest) GetPaymentMethodOk() (*GuestPaymentMethodInitializeRequestPaymentMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *GuestPaymentMethodInitializeRequest) SetPaymentMethod(v GuestPaymentMethodInitializeRequestPaymentMethod) {
	o.PaymentMethod = v
}

func (o GuestPaymentMethodInitializeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuestPaymentMethodInitializeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cart"] = o.Cart
	toSerialize["payment_method"] = o.PaymentMethod
	return toSerialize, nil
}

type NullableGuestPaymentMethodInitializeRequest struct {
	value *GuestPaymentMethodInitializeRequest
	isSet bool
}

func (v NullableGuestPaymentMethodInitializeRequest) Get() *GuestPaymentMethodInitializeRequest {
	return v.value
}

func (v *NullableGuestPaymentMethodInitializeRequest) Set(val *GuestPaymentMethodInitializeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuestPaymentMethodInitializeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuestPaymentMethodInitializeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuestPaymentMethodInitializeRequest(val *GuestPaymentMethodInitializeRequest) *NullableGuestPaymentMethodInitializeRequest {
	return &NullableGuestPaymentMethodInitializeRequest{value: val, isSet: true}
}

func (v NullableGuestPaymentMethodInitializeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuestPaymentMethodInitializeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


